apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: anubis-kafka-kill-random-pod
  namespace: myproject
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - myproject
    labelSelectors:
      strimzi.io/kind: "Kafka"
      strimzi.io/broker-role: "true"
  duration: "5m"
