apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-3-pods-failure
  namespace: strimzi-kafka
spec:
  action: pod-failure
  mode: fixed
  selector:
    namespaces:
      - strimzi-kafka
    labelSelectors:
      strimzi.io/kind: "Kafka"
      strimzi.io/broker-role: "true"
  value: "3"
  duration: "5m"
