apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-node-intense-stress
  namespace: strimzi-kafka
spec:
  mode: one
  selector:
    namespaces:
      - strimzi-kafka
    labelSelectors:
      strimzi.io/kind: "Kafka"
      strimzi.io/broker-role: "true"
  stressors:
    cpu:
      workers: 4  # Increase the number of workers to generate a higher CPU load
      load: 100  # Represents full load on two CPU cores
    memory:
      workers: 4  # More workers to generate memory stress
      size: '2GB' # Occupy more memory
  duration: '5m' # Longer duration for the stress test
